import type { CreditRecord, User, DashboardStats } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'James Harrington',
    email: 'j.harrington@carboncredit.io',
    role: 'Admin',
    userType: 'Default User',
    status: 'Active',
    joinedDate: '2025-01-15',
  },
  {
    id: '2',
    name: 'Sophia Chen',
    email: 's.chen@carboncredit.io',
    role: 'Manager',
    userType: 'Future User Lvl 1',
    status: 'Active',
    joinedDate: '2025-03-02',
  },
  {
    id: '3',
    name: 'Marcus Webb',
    email: 'm.webb@carboncredit.io',
    role: 'Manager',
    userType: 'Future User Lvl 1',
    status: 'Active',
    joinedDate: '2025-04-10',
  },
  {
    id: '4',
    name: 'Priya Nair',
    email: 'p.nair@carboncredit.io',
    role: 'Viewer',
    userType: 'Future User Lvl 2',
    status: 'Pending',
    joinedDate: '2025-06-18',
  },
  {
    id: '5',
    name: 'Lucas Fontaine',
    email: 'l.fontaine@carboncredit.io',
    role: 'Viewer',
    userType: 'Default User',
    status: 'Inactive',
    joinedDate: '2024-11-30',
  },
  {
    id: '6',
    name: 'Aisha Okonkwo',
    email: 'a.okonkwo@carboncredit.io',
    role: 'Manager',
    userType: 'Future User Lvl 2',
    status: 'Active',
    joinedDate: '2025-08-22',
  },
];

export const mockCreditRecords: CreditRecord[] = [
  // Red – Operations In Progress
  {
    id: 'r1',
    name: 'Permian Basin Alpha',
    field: 'West Texas',
    credits: 12400,
    progress: 28,
    marketValue: 310000,
    status: 'red',
    lastUpdated: '2026-04-01',
  },
  {
    id: 'r2',
    name: 'Eagle Ford Beta',
    field: 'South Texas',
    credits: 8750,
    progress: 45,
    marketValue: 218750,
    status: 'red',
    lastUpdated: '2026-03-29',
  },
  {
    id: 'r3',
    name: 'Bakken Delta',
    field: 'North Dakota',
    credits: 15200,
    progress: 17,
    marketValue: 380000,
    status: 'red',
    lastUpdated: '2026-04-03',
  },
  {
    id: 'r4',
    name: 'DJ Basin Gamma',
    field: 'Colorado',
    credits: 6300,
    progress: 62,
    marketValue: 157500,
    status: 'red',
    lastUpdated: '2026-03-28',
  },
  // Yellow – Credit Certification
  {
    id: 'y1',
    name: 'Anadarko Sigma',
    field: 'Oklahoma',
    credits: 21500,
    progress: 74,
    marketValue: 537500,
    status: 'yellow',
    lastUpdated: '2026-03-25',
  },
  {
    id: 'y2',
    name: 'Haynesville Omega',
    field: 'Louisiana',
    credits: 17800,
    progress: 88,
    marketValue: 445000,
    status: 'yellow',
    lastUpdated: '2026-04-02',
  },
  {
    id: 'y3',
    name: 'Marcellus Theta',
    field: 'Pennsylvania',
    credits: 9400,
    progress: 55,
    marketValue: 235000,
    status: 'yellow',
    lastUpdated: '2026-03-30',
  },
  {
    id: 'y4',
    name: 'Niobrara Kappa',
    field: 'Wyoming',
    credits: 13100,
    progress: 91,
    marketValue: 327500,
    status: 'yellow',
    lastUpdated: '2026-04-04',
  },
  // Green – Credits Issued
  {
    id: 'g1',
    name: 'Gulf Coast Prime',
    field: 'Texas Coast',
    credits: 45000,
    progress: 100,
    marketValue: 1125000,
    status: 'green',
    lastUpdated: '2026-02-14',
  },
  {
    id: 'g2',
    name: 'Mid-Continent Apex',
    field: 'Kansas',
    credits: 33200,
    progress: 100,
    marketValue: 830000,
    status: 'green',
    lastUpdated: '2026-01-28',
  },
  {
    id: 'g3',
    name: 'Rockies Summit',
    field: 'Montana',
    credits: 28600,
    progress: 100,
    marketValue: 715000,
    status: 'green',
    lastUpdated: '2026-03-10',
  },
  {
    id: 'g4',
    name: 'Appalachian Vault',
    field: 'West Virginia',
    credits: 19800,
    progress: 100,
    marketValue: 495000,
    status: 'green',
    lastUpdated: '2026-03-22',
  },
  {
    id: 'g5',
    name: 'Uinta Basin Reserve',
    field: 'Utah',
    credits: 52100,
    progress: 100,
    marketValue: 1302500,
    status: 'green',
    lastUpdated: '2026-02-05',
  },
];

export const mockDashboardStats: DashboardStats = {
  activeWells: 38,
  totalCredits: mockCreditRecords.reduce((sum, r) => sum + r.credits, 0),
  projectedMktValue: mockCreditRecords.reduce((sum, r) => sum + r.marketValue, 0),
  redCount: mockCreditRecords.filter((r) => r.status === 'red').length,
  yellowCount: mockCreditRecords.filter((r) => r.status === 'yellow').length,
  greenCount: mockCreditRecords.filter((r) => r.status === 'green').length,
};
